document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.musestar.top\/\"><img src=\"https:\/\/www.musestar.top\/ms.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.musestar.top\/\">首页<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"https:\/\/www.musestar.top\/animation\">缪斯星动漫<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.musestar.top\/movie\">缪斯星影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.musestar.top\/comic\">缪斯星漫画<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.musestar.top\/ecy\">二次元图库<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"https:\/\/game.musestar.top\" >缪斯星游戏<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/www.musestar.top\/musestar\" >缪斯星官方<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/www.musestar.top\/muse\" >缪斯星专区<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");