document.write("    <div class=\"deng-box2\">");
document.write("        <div class=\"deng\">");
document.write("            <div class=\"xian\"><\/div>");
document.write("            <div class=\"deng-a\">");
document.write("                <div class=\"deng-b\">");
document.write("                    <div class=\"deng-t\">新<\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"shui shui-a\">");
document.write("                <div class=\"shui-c\"><\/div>");
document.write("                <div class=\"shui-b\"><\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <div class=\"deng-box3\">");
document.write("        <div class=\"deng\">");
document.write("            <div class=\"xian2\"><\/div>");
document.write("            <div class=\"deng-a\">");
document.write("                <div class=\"deng-b\">");
document.write("                    <div class=\"deng-t\">年<\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"shui shui-a\">");
document.write("                <div class=\"shui-c\"><\/div>");
document.write("                <div class=\"shui-b\"><\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <div class=\"deng-box1\">");
document.write("        <div class=\"deng\">");
document.write("            <div class=\"xian\"><\/div>");
document.write("            <div class=\"deng-a\">");
document.write("                <div class=\"deng-b\">");
document.write("                    <div class=\"deng-t\">快<\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"shui shui-a\">");
document.write("                <div class=\"shui-c\"><\/div>");
document.write("                <div class=\"shui-b\"><\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <div class=\"deng-box\">");
document.write("        <div class=\"deng\">");
document.write("            <div class=\"xian2\"><\/div>");
document.write("            <div class=\"deng-a\">");
document.write("                <div class=\"deng-b\">");
document.write("                    <div class=\"deng-t\">乐<\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"shui shui-a\">");
document.write("                <div class=\"shui-c\"><\/div>");
document.write("                <div class=\"shui-b\"><\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <style type=\"text\/css\">");
document.write("        .deng-box {");
document.write("            position: fixed;");
document.write("            top: 15px;");
document.write("            right: -20px;");
document.write("            z-index: 9999;");
document.write("            pointer-events: none");
document.write("        }");
document.write("");
document.write("        .deng-box1 {");
document.write("            position: fixed;");
document.write("            top: 10px;");
document.write("            right: 150px;");
document.write("            z-index: 9999;");
document.write("            pointer-events: none");
document.write("        }");
document.write("");
document.write("        .deng-box2 {");
document.write("            position: fixed;");
document.write("            top: 10px;");
document.write("            left: -20px;");
document.write("            z-index: 9999;");
document.write("            pointer-events: none");
document.write("        }");
document.write("");
document.write("        .deng-box3 {");
document.write("            position: fixed;");
document.write("            top: 15px;");
document.write("            left: 150px;");
document.write("            z-index: 9999;");
document.write("            pointer-events: none");
document.write("        }");
document.write("");
document.write("        .deng-box1 .deng,");
document.write("        .deng-box3 .deng {");
document.write("            position: relative;");
document.write("            width: 120px;");
document.write("            height: 90px;");
document.write("            margin: 50px;");
document.write("            background: #d8000f;");
document.write("            background: rgba(216, 0, 15, .8);");
document.write("            border-radius: 50% 50%;");
document.write("            -webkit-transform-origin: 50% -100px;");
document.write("            -webkit-animation: swing 5s infinite ease-in-out;");
document.write("            box-shadow: -5px 5px 30px 4px #fc903d");
document.write("        }");
document.write("");
document.write("        .deng {");
document.write("            position: relative;");
document.write("            width: 120px;");
document.write("            height: 90px;");
document.write("            margin: 50px;");
document.write("            background: #d8000f;");
document.write("            background: rgba(216, 0, 15, .8);");
document.write("            border-radius: 50% 50%;");
document.write("            -webkit-transform-origin: 50% -100px;");
document.write("            -webkit-animation: swing 3s infinite ease-in-out;");
document.write("            box-shadow: -5px 5px 50px 4px #fa6c00");
document.write("        }");
document.write("");
document.write("        .deng-a {");
document.write("            width: 100px;");
document.write("            height: 90px;");
document.write("            background: #d8000f;");
document.write("            background: rgba(216, 0, 15, .1);");
document.write("            margin: 12px 8px 8px 8px;");
document.write("            border-radius: 50% 50%;");
document.write("            border: 2px solid #dc8f03");
document.write("        }");
document.write("");
document.write("        .deng-b {");
document.write("            width: 45px;");
document.write("            height: 90px;");
document.write("            background: #d8000f;");
document.write("            background: rgba(216, 0, 15, .1);");
document.write("            margin: -4px 8px 8px 26px;");
document.write("            border-radius: 50% 50%;");
document.write("            border: 2px solid #dc8f03");
document.write("        }");
document.write("");
document.write("        .xian {");
document.write("            position: absolute;");
document.write("            top: -60px;");
document.write("            left: 60px;");
document.write("            width: 2px;");
document.write("            height: 60px;");
document.write("            background: #dc8f03");
document.write("        }");
document.write("");
document.write("        .xian2 {");
document.write("            position: absolute;");
document.write("            top: -65px;");
document.write("            left: 60px;");
document.write("            width: 2px;");
document.write("            height: 65px;");
document.write("            background: #dc8f03");
document.write("        }");
document.write("");
document.write("        .shui-a {");
document.write("            position: relative;");
document.write("            width: 5px;");
document.write("            height: 20px;");
document.write("            margin: -5px 0 0 59px;");
document.write("            -webkit-animation: swing 4s infinite ease-in-out;");
document.write("            -webkit-transform-origin: 50% -45px;");
document.write("            background: orange;");
document.write("            border-radius: 0 0 5px 5px");
document.write("        }");
document.write("");
document.write("        .shui-b {");
document.write("            position: absolute;");
document.write("            top: 14px;");
document.write("            left: -2px;");
document.write("            width: 10px;");
document.write("            height: 10px;");
document.write("            background: #dc8f03;");
document.write("            border-radius: 50%");
document.write("        }");
document.write("");
document.write("        .shui-c {");
document.write("            position: absolute;");
document.write("            top: 18px;");
document.write("            left: -2px;");
document.write("            width: 10px;");
document.write("            height: 35px;");
document.write("            background: orange;");
document.write("            border-radius: 0 0 0 5px");
document.write("        }");
document.write("");
document.write("        .deng:before {");
document.write("            position: absolute;");
document.write("            top: -7px;");
document.write("            left: 29px;");
document.write("            height: 12px;");
document.write("            width: 60px;");
document.write("            content: \" \";");
document.write("            display: block;");
document.write("            z-index: 999;");
document.write("            border-radius: 5px 5px 0 0;");
document.write("            border: solid 1px #dc8f03;");
document.write("            background: orange;");
document.write("            background: linear-gradient(to right, #dc8f03, orange, #dc8f03, orange, #dc8f03)");
document.write("        }");
document.write("");
document.write("        .deng:after {");
document.write("            position: absolute;");
document.write("            bottom: -7px;");
document.write("            left: 10px;");
document.write("            height: 12px;");
document.write("            width: 60px;");
document.write("            content: \" \";");
document.write("            display: block;");
document.write("            margin-left: 20px;");
document.write("            border-radius: 0 0 5px 5px;");
document.write("            border: solid 1px #dc8f03;");
document.write("            background: orange;");
document.write("            background: linear-gradient(to right, #dc8f03, orange, #dc8f03, orange, #dc8f03)");
document.write("        }");
document.write("");
document.write("        .deng-t {");
document.write("            font-family: 华文行楷, Arial, Lucida Grande, Tahoma, sans-serif;");
document.write("            font-size: 3.2rem;");
document.write("            color: #dc8f03;");
document.write("            font-weight: 700;");
document.write("            line-height: 85px;");
document.write("            text-align: center");
document.write("        }");
document.write("");
document.write("        .night .deng-box,");
document.write("        .night .deng-box1,");
document.write("        .night .deng-t {");
document.write("            background: 0 0 !important");
document.write("        }");
document.write("");
document.write("        @-moz-keyframes swing {");
document.write("            0% {");
document.write("                -moz-transform: rotate(-10deg)");
document.write("            }");
document.write("");
document.write("            50% {");
document.write("                -moz-transform: rotate(10deg)");
document.write("            }");
document.write("");
document.write("            100% {");
document.write("                -moz-transform: rotate(-10deg)");
document.write("            }");
document.write("        }");
document.write("");
document.write("        @-webkit-keyframes swing {");
document.write("            0% {");
document.write("                -webkit-transform: rotate(-20deg)");
document.write("            }");
document.write("");
document.write("            50% {");
document.write("                -webkit-transform: rotate(18deg)");
document.write("            }");
document.write("");
document.write("            100% {");
document.write("                -webkit-transform: rotate(-20deg)");
document.write("            }");
document.write("        }");
document.write("    <\/style>");
