document.write("    <div class=\"side r\">");
document.write("    <div class=\"firs l\">");
document.write("    <div class=\"dtit\">");
document.write("        <h2>共收到127.1元<u><a href=\"https:\/\/musestarv.github.io\/pay\" >发电赞助<\/a><\/u><\/h2>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("	<div class=\"tlist\">");
document.write("<\/div>      ");
document.write("    <div class=\"side r\">");
document.write("    <div class=\"firs l\">");
document.write("    <div class=\"dtit\">");
document.write("        <h2>网站加载慢问题<\/h2>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("	<div class=\"tlist\">");
document.write("                <a>请连接VPN或使用“Watt Toolkit”软件加速“Github.io”<\/a>");
document.write("<\/div><\/div>      ");
