document.write("    <div class=\"foot\">");
document.write("        <div class=\"footer-logo\">");
document.write("            <img src=\"https://s1.imagehub.cc/images/2025/03/14/75aca0f31bd08308fa150301c0ec6589.png\" alt=\"MUSESTAR Logo\">");
document.write("        </div>");
document.write("        <div class=\"footer-divider\"></div>");
document.write("        <a href=\"https://musestar.cc/\">© <script> document.write('' + (new Date()).getFullYear()) </script> MUSESTAR</a>");
document.write("        <a href=\"https://icp.gov.moe/?keyword=20226956\" target=\"_blank\">萌ICP备20226956号</a>");
document.write("        <a href=\"https://stats.uptimerobot.com/NJ9gBiMZ7D\" target=\"_blank\">缪斯星服务状态</a>");
document.write("        <a href=\"mailto:admin@musestar.cc\" target=\"_blank\">联系邮箱admin@musestar.cc</a>");
document.write("        <div class=\"footer-divider\"></div>");
document.write("        <div class=\"footer-social\">");
document.write("            <a href=\"#\" title=\"微博\"><i class=\"fab fa-weibo\"></i></a>");
document.write("            <a href=\"#\" title=\"微信\"><i class=\"fab fa-weixin\"></i></a>");
document.write("            <a href=\"#\" title=\"QQ\"><i class=\"fab fa-qq\"></i></a>");
document.write("            <a href=\"#\" title=\"GitHub\"><i class=\"fab fa-github\"></i></a>");
document.write("        </div>");
document.write("        <div>本站已运行 <span class=\"brand\" id=\"runtime\"></span></div>");
document.write("        <script type=\"text/javascript\">");
document.write("	        function show_runtime(){");
document.write("		        window.setTimeout(\"show_runtime()\",1000);");
document.write("		        X=new Date(\"04/25/2022 00:00:00\");");
document.write("		        Y=new Date();");
document.write("		        T=(Y.getTime()-X.getTime());");
document.write("		        M=24*60*60*1000;");
document.write("		        a=T/M;");
document.write("		        A=Math.floor(a);");
document.write("		        b=(a-A)*24;");
document.write("		        B=Math.floor(b);");
document.write("		        c=(b-B)*60;");
document.write("		        C=Math.floor((b-B)*60);");
document.write("		        D=Math.floor((c-C)*60);");
document.write("		        runtime.innerHTML=A+\"天\"+B+\"小时\"+C+\"分\"+D+\"秒\"");
document.write("	        }show_runtime();");
document.write("        </script>");
document.write("    </div>"); 