document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestarv.github.io\/\"><img src=\"https:\/\/musestarv.github.io\/ms.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestarv.github.io\/\">首页<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestarv.github.io\/animation\">缪斯星动漫<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"https:\/\/musestarv.github.io\/movie\">缪斯星影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestarv.github.io\/ecy\">二次元图库<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"https:\/\/musestarv.github.io\/musestar\" >缪斯星官方<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/musestarv.github.io\/pay\" >发电赞助<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");