document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"\/\"><img src=\"\/favicon.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"\/\">首页<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"\/animation\">缪斯星动漫<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"\/movie\">缪斯星影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"http:\/\/search.musestar.cc\">缪斯星搜索<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"\/musestar\" >缪斯星官方<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"\/muse\" >缪斯星专区<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\" \" >缪斯星暂无<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");