document.write("	        <ul class=\"top_nav clearfix\">");
document.write("                				<li class=\"active\"><a href=\"https:\/\/musestar.cc\/animation\" >缪斯星动漫<\/a><\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("		<div class=\"head_user\">");
document.write("		    <ul>");
document.write("	        	<li><a href=\"https:\/\/musestar.cc\"><font size=\"1\">首页<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/musestar.cc\/animation\" ><font size=\"1\">缪斯星动漫<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/musestar.cc\/movie\" ><font size=\"1\">缪斯星影视<\/font><\/a><\/li>");
document.write("                <li><a href=\"http:\/\/search.musestar.cc\" ><font size=\"1\">缪斯星搜索<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/musestar.cc\/musestar\" ><font size=\"1\">缪斯星官方<\/font><\/a><\/li>");
document.write("                            <\/ul>");