document.write("	        <ul class=\"top_nav clearfix\">");
document.write("                				<li class=\"active\"><a href=\"https:\/\/www.musestar.top\/animation\" >缪斯星动漫<\/a><\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("		<div class=\"head_user\">");
document.write("		    <ul>");
document.write("	        	<li><a href=\"https:\/\/www.musestar.top\"><font size=\"1\">首页<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.musestar.top\/animation\" ><font size=\"1\">缪斯星动漫<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.musestar.top\/movie\" ><font size=\"1\">缪斯星影视<\/font><\/a><\/li>");
document.write("                <li><a href=\"http:\/\/www.musestars.top\" ><font size=\"1\">缪斯星搜索<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/www.musestar.top\/musestar\" ><font size=\"1\">缪斯星官方<\/font><\/a><\/li>");
document.write("				<li><a href=\" \" ><font size=\"1\">缪斯星暂无<\/font><\/a><\/li>");
document.write("                            <\/ul>");