document.write("	        <ul class=\"top_nav clearfix\">");
document.write("                				<li class=\"active\"><a href=\"https:\/\/www.musestar.top\/comic\" >缪斯星漫画<\/a><\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("		<div class=\"head_user\">");
document.write("		    <ul>");
document.write("	        	<li><a href=\"https:\/\/www.musestar.top\/main\"><font size=\"1\">首页<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.musestar.top\/animation\" ><font size=\"1\">缪斯星动漫<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.musestar.top\/movie\" ><font size=\"1\">缪斯星影视<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.musestar.top\/comic\" ><font size=\"1\">缪斯星漫画<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.musestar.top\/ecy\" ><font size=\"1\">二次元图库<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/game.musestar.top\" ><font size=\"1\">缪斯星游戏<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/www.musestar.top\/musestar\" ><font size=\"1\">缪斯星官方<\/font><\/a><\/li>");
document.write("                            <\/ul>");