document.write("	        <ul class=\"top_nav clearfix\">");
document.write("	        	                <li><a href=\"https:\/\/musestarv.github.io\/\">首页<\/a><\/li>");
document.write("                				<li><a href=\"https:\/\/musestarv.github.io\/animation\" >缪斯星动漫<\/a><\/li>");
document.write("								<li class=\"active\"><a href=\"https:\/\/musestarv.github.io\/movie\" >缪斯星影视<\/a><\/li>");
document.write("								<li><a href=\"https:\/\/musestarv.github.io\/ecy\" >二次元图库<\/a><\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("		<div class=\"head_user\">");
document.write("		    <ul>");
document.write("                <li><a href=\"https:\/\/musestarv.github.io\/animation\" ><font size=\"1\">缪斯星动漫<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/musestarv.github.io\/movie\" ><font size=\"1\">缪斯星影视<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/musestarv.github.io\/ecy\" ><font size=\"1\">二次元图库<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/musestarv.github.io\/musestar\" ><font size=\"1\">缪斯星官方<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/musestarv.github.io\/pay\" ><font size=\"1\">发电赞助<\/font><\/a><\/li>");
document.write("                            <\/ul>");