document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.cc\/animation\/mushokutensei\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/07\/18\/mushokutensei.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">1<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">预计共12集<\/span>");
document.write("                                            <h4 class=\"title\">无职转生Ⅱ<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-07-02<\/p>");
document.write("                                        <p class=\"vodlist_sub\">日本\/奇幻<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星动漫更新中<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");

document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.cc\/animation\/zom100\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/07\/18\/zom100.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num2\">2<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">预计共12集<\/span>");
document.write("                                            <h4 class=\"title\">僵尸百分百<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-07-09<\/p>");
document.write("                                        <p class=\"vodlist_sub\">日本\/喜剧<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星动漫更新中<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");

document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.cc\/animation\/ainoidenshi\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/07\/18\/ainoidenshi.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num3\">3<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">预计共12集<\/span>");
document.write("                                            <h4 class=\"title\">AI电子基因<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-07-07<\/p>");
document.write("                                        <p class=\"vodlist_sub\">日本\/科幻<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星动漫更新中<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");