document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("           <a href=\" https:\/\/www.musestar.cc\/main\">© 2024 MUSESTAR<\/a><br>");
document.write("<a href=\"https:\/\/icp.gov.moe\/?keyword=20226956\" target=\"_blank\">萌ICP备20226956号<\/a><br>");
document.write("<a href=\"https:\/\/www.musestar.cc\/sitemap.xml\" >网站地图<\/a><br>");
document.write("<a>未经本站授权禁止转载、摘编、复制或建立镜像。本站只提供WEB页面服务，本站不存储、不制作任何视频及图像，不承担任何由于内容的合法性及健康性所引起的争议和法律责任。<\/a>");
document.write("<p>已运行：<span class=\"brand\" id=\"runtime\"><\/span><\/p>		");
document.write("<script type=\"text\/javascript\">");
document.write("	function show_runtime(){");
document.write("		window.setTimeout(\"show_runtime()\",1000);");
document.write("		X=new Date(\"04\/25\/2022 00:00:00\");");
document.write("		Y=new Date();");
document.write("		T=(Y.getTime()-X.getTime());");
document.write("		M=24*60*60*1000;");
document.write("		a=T\/M;");
document.write("		A=Math.floor(a);");
document.write("		b=(a-A)*24;");
document.write("		B=Math.floor(b);");
document.write("		c=(b-B)*60;");
document.write("		C=Math.floor((b-B)*60);");
document.write("		D=Math.floor((c-C)*60);");
document.write("		runtime.innerHTML=A+\"天\"+B+\"小时\"+C+\"分\"+D+\"秒\"");
document.write("	}show_runtime();");
document.write("<\/script>");
