document.write(" <div class=\"blank\"><\/div>");
document.write("        <div class=\"botit\">");
document.write("          <h2>温馨提示<\/h2><\/div>");
document.write("        <div class=\"info\"><font color=\"red\">请勿相信视频内的任何广告<\/font><\/div>");
document.write("        <div class=\"info\"><font color=\"red\">右上角请勿相信视频内的任何广告！点击缪斯星官方求片报错、赞助支持、加入交流群<\/font><\/div>");
document.write("      <\/div>");
document.write("         <\/div>");
document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("           <a href=\" https:\/\/www.musestar.cc\">© 2024 MUSESTAR<\/a><br>");
document.write("           <a href=\" https:\/\/www.musestar.cc\">© 2024 LycoriXradiaTa<\/a><br>");
document.write("<a href=\"https:\/\/icp.gov.moe\/?keyword=20226956\" target=\"_blank\">萌ICP备20226956号<\/a><br>");
document.write("<p>本站已坚持 <span class=\"brand\" id=\"runtime\"><\/span><\/p>		");
document.write("<a id=\"hitokoto\">一言获取中...<\/a>");
document.write("<script type=\"text\/javascript\">");
document.write("	function show_runtime(){");
document.write("		window.setTimeout(\"show_runtime()\",1000);");
document.write("		X=new Date(\"04\/25\/2022 00:00:00\");");
document.write("		Y=new Date();");
document.write("		T=(Y.getTime()-X.getTime());");
document.write("		M=24*60*60*1000;");
document.write("		a=T\/M;");
document.write("		A=Math.floor(a);");
document.write("		b=(a-A)*24;");
document.write("		B=Math.floor(b);");
document.write("		c=(b-B)*60;");
document.write("		C=Math.floor((b-B)*60);");
document.write("		D=Math.floor((c-C)*60);");
document.write("		runtime.innerHTML=A+\"天\"+B+\"小时\"+C+\"分\"+D+\"秒\"");
document.write("	}show_runtime();");
document.write("<\/script>");
document.write("    <script>");
document.write("        fetch('https:\/\/v1.hitokoto.cn')");
document.write("          .then(function (res){");
document.write("            return res.json();");
document.write("          })");
document.write("          .then(function (data) {");
document.write("            var hitokoto = document.getElementById('hitokoto');");
document.write("            hitokoto.innerText = data.hitokoto; ");
document.write("          })");
document.write("          .catch(function (err) {");
document.write("            console.error(err);");
document.write("          })");
document.write("      <\/script>");
