document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.top\/animation\/TentenKakume\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/01\/04\/92834316efdfec96df02ce6049d159be.jpeg);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">1<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">预计共12集<\/span>");
document.write("                                            <h4 class=\"title\">转生王女与天才千金的魔法革命<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-01-04<\/p>");
document.write("                                        <p class=\"vodlist_sub\">日本\/奇幻<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");
