document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.cc\/teleplay\/PunchOut\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/02\/01\/b1454e2a4abca9d53dafd97baf3b912c.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">1<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">共39集<\/span>");
document.write("                                            <h4 class=\"title\">狂飙<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-01-14<\/p>");
document.write("                                        <p class=\"vodlist_sub\">中国\/犯罪<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星影视已完结<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.cc\/film\/TheWanderingEarth2\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/01\/02\/49348cf0d5976eb8567f845bb616ae38.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">2<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">注意：目前为TC版<\/span>");
document.write("                                            <h4 class=\"title\">流浪地球2<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-01-22<\/p>");
document.write("                                        <p class=\"vodlist_sub\">中国\/科幻<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星影视上映<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.cc\/teleplay\/3body\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/01\/16\/5e32727ab66df0680b3a2ce0a40375c8.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">3<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">共30集<\/span>");
document.write("                                            <h4 class=\"title\">三体<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-01-15<\/p>");
document.write("                                        <p class=\"vodlist_sub\">中国\/科幻<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星影视已完结<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");