document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.top\/animation\/SaikyouOnmyouji\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/01\/09\/e7f0523688703d5148f03d3df7f4121d.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">1<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">预计共12集<\/span>");
document.write("                                            <h4 class=\"title\">最强阴阳师的异世界转生记<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2023-01-07<\/p>");
document.write("                                        <p class=\"vodlist_sub\">日本\/奇幻<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星动漫更新中<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("                            <li class=\"ranklist_item\">");
document.write("                                <a href=\"https:\/\/www.musestar.top\/teleplay\/TheGoodDoctor6\">");
document.write("                                    <div class=\"ranklist_img\">");
document.write("                                        <div class=\"ranklist_thumb  lazyload\"");
document.write("                                             style=\"background-image: url(https:\/\/s1.imagehub.cc\/images\/2023\/01\/08\/71b2670abc2bfe992f18c98290b98094.webp);\">");
document.write("                                            <span class=\"play hidden_xs\"><\/span>");
document.write("                                            <span class=\"part_nums part_num1\">2<\/span>");
document.write("                                        <\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"ranklist_txt\">");
document.write("                                        <div class=\"pannel_head clearfix\">");
document.write("                                            <span class=\"text_muted pull_right\">共22集<\/span>");
document.write("                                            <h4 class=\"title\">良医第六季<\/h4>");
document.write("                                        <\/div>");
document.write("                                        <p class=\"vodlist_sub\">2022-10-03<\/p>");
document.write("                                        <p class=\"vodlist_sub\">美国\/剧情<\/p>");
document.write("                                        <p class=\"vodlist_sub\">缪斯星影视更新中<\/p>");
document.write("                                    <\/div>");
document.write("                                <\/a>");
document.write("                            <\/li>");