document.write("           <li>");
document.write("               <a href=\"https:\/\/www.musestar.cc\/teleplay\/moonknight\/01\" title=\"第1集\" target=\"_self\">第1集<\/a>");
document.write("            <\/li>     ");
document.write("           <li>");
document.write("               <a href=\"https:\/\/www.musestar.cc\/teleplay\/moonknight\/02\" title=\"第2集\" target=\"_self\">第2集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/www.musestar.cc\/teleplay\/moonknight\/03\" title=\"第3集\" target=\"_self\">第3集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/www.musestar.cc\/teleplay\/moonknight\/04\" title=\"第4集\" target=\"_self\">第4集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/www.musestar.cc\/teleplay\/moonknight\/05\" title=\"第5集\" target=\"_self\">第5集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/www.musestar.cc\/teleplay\/moonknight\/06\" title=\"第6集\" target=\"_self\">第6集<\/a>");
document.write("            <\/li>");